services:
  server:
    platform: linux/amd64
    image: ghcr.io/vrevolverrr/peepal-backend:latest
    build:
      context: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000