name: peepal
description: "PeePal is a community driven crowd sourced toilet finding application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  flutter_animate: ^4.5.2
  geolocator: ^13.0.2
  equatable: ^2.0.7
  rxdart: ^0.28.0
  logging: ^1.3.0
  carousel_slider: ^4.2.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  http: ^1.1.0
  maps_toolkit: ^3.1.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  bloc_concurrency: ^0.3.0
  auto_size_text: ^3.0.0
  apple_maps_flutter: ^1.4.0
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: MazzardH
      fonts:
        - asset: assets/fonts/MazzardH/MazzardH-Bold.ttf
          weight: 700
        - asset: assets/fonts/MazzardH/MazzardH-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MazzardH/MazzardH-Medium.ttf
          weight: 500

flutter_launcher_icons:
  ios: true
  image_path: "assets/icon/icon.png"